name = "talk-to-me-nicely"
compatibility_date = "2024-11-01"
pages_build_output_dir = "public"

[env.production]
name = "talk-to-me-nicely"

[[d1_databases]]
binding = "DB"
database_name = "coparenting-db"
database_id = "565f55aa-bac1-4de2-a9ac-55023cbc1925"
preview_database_id = "565f55aa-bac1-4de2-a9ac-55023cbc1925"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "coparenting-attachments"
preview_bucket_name = "coparenting-attachments-preview"

[build]
command = ""

